export const WAITING_FOR_PLAYER = 'WAITING_FOR_PLAYER';
export const GAME_ENDED = 'GAME_ENDED';
export const GAME_ENDED_FROM_ERROR = 'GAME_ENDED_FROM_ERROR';
export const IN_PROGRESS = 'IN_PROGRESS';
export const WAITING_TO_START = 'WAITING_TO_START';
