export const WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS';
export const GAME_ENDED = 'GAME_ENDED';
export const GAME_ENDED_FROM_ERROR = 'GAME_ENDED_FROM_ERROR';
export const IN_PROGRESS = 'IN_PROGRESS';
